### ISSUE TITLE
move liquidity from osmosis to bostrom

### ISSUE THREAD

**Issue by mastercyb** [cybercongress/cybercongress#475]
This project is the first step to Bostrom hub. Recently Osmosis removed BOOT incentives. Thanks to portal most of users came from our channels, not from Osmosis. We have to stop feed external system with transactions. We have all we need to boost internal ecosystem. The only reason why we need some liquidity on osmosis is price discovery on aggregators.

- [x] move 80% of congress liquidity to Bostrom
- [x] create channels with JUNO, EVMOS, GRAV
- [x] add JUNO, EVMOS, GRAV, ION to #cyb
- [x] retire pool 8 and 9 in #cyb
- [x] migrate old atom channel to the new channel in #cyb
- [x] add pools newATOM/H, JUNO/H, EVMOS/H, GRAV/H, ION/H
- [x] support new pools in #cyb
- [x] https://github.com/cybercongress/cyb/issues/629
- [ ] https://github.com/cybercongress/cyb/issues/634
- [ ] add swap indexer in #cyberindex
- [ ] create doc about listing of teleport #cyberindex
- [ ] listing of teleport in coingecko and coinmarketcap
- [ ] after that cybercongress can move rest liquidity from osmosis to teleport

**Comment by SaveTheAles** [comment]
![image](https://user-images.githubusercontent.com/36516972/179842696-5c1e2f38-846f-4729-804d-a4641db5e7c8.png)

**Comment by mastercyb** [comment]
need to design mm strategy
